@baseUrl = http://172.18.0.5:6400

### Get API Health
GET {{baseUrl}}/api/v1/health

### List All emails for a given customer
GET {{baseUrl}}/api/v1/todos

### Get information for a given customer and email
GET {{baseUrl}}/api/v1/customers/d73288b1-7bb0-435c-a434-9d19830d64c7/emails/1

### Create scan request
POST {{baseUrl}}/api/v1/customers/d73288b1-7bb0-435c-a434-9d19830d64c7/emails
Content-Type: application/json

{
  "metadata" : {
    "spamhammer" : "1|14"
  },
  "contents" : {
    "subject" : "Important information about your account.",
    "from" : "foo@uq.edu.au",
    "to" : "fred@uq.edu.au",
    "body" : "Dear Valued Person,\nPlease click my links, https://scam-check.uq.edu.au and https://scam-check.uq.edu.au"
  }
}

### Get malicious senders of emails
GET {{baseUrl}}/api/v1/customers/d73288b1-7bb0-435c-a434-9d19830d64c7/reports/actors

### Get the domains that appeared in malicious emails
GET {{baseUrl}}/api/v1/customers/d73288b1-7bb0-435c-a434-9d19830d64c7/reports/domains

### Get the users who recieved malicious emails
GET {{baseUrl}}/api/v1/customers/d73288b1-7bb0-435c-a434-9d19830d64c7/reports/recipients

### create ical job
POST {{baseUrl}}/api/v1/todos/ical
Content-Type: application/json

{ 
 "task_id": "1", 
 "task_url": "http://localhost:6400/api/v1/todos/ical/1/status" 
}

### Get ical job by number
GET {{baseUrl}}/todos/ical/1/status
